### PR TITLE
Username Characters Length Limitation & Overflow Fix

### PR DESCRIPTION
**Pull request by mdPial**
This solve the issue #9 

- [x] Added line break in overflow
image

- [x] Added character limit up to 40
image

### CODE REVIEW

**Comment by fibanneacci** [comment]
Hi, looks great, thank you again! One minor thing: could we combine the error messages for "please enter a username to continue" and "please enter a username between 1 and 40 characters" into a single message?

**Comment by mdPial** [comment]
> Hi, looks great, thank you again! One minor thing: could we combine the error messages for "please enter a username to continue" and "please enter a username between 1 and 40 characters" into a single message?

Yes. I will update the code.

**Comment by mdPial** [comment]
I have updated please check. If it's okay or not.

**Comment by fibanneacci** [comment]
Looks good, thank you again!

**Comment by mdPial** [comment]
> Looks good, thank you again!

welcome 😄

**Pull request merged**
